$APP_PACKAGE -> $WEBAPP_PACKAGE; rails_ctl_setup like others

diff --git a/jobs/webapp/templates/ctl_setup.sh.erb b/jobs/webapp/templates/ctl_setup.sh.erb
--- a/jobs/webapp/templates/ctl_setup.sh.erb
+++ b/jobs/webapp/templates/ctl_setup.sh.erb
@@ -7,12 +7,23 @@
 set -e # exit immediately if a simple command exits with a non-zero status
 set -u # report the usage of uninitialized variables
 
-source /var/vcap/jobs/<%= name %>/bin/ctl_utils.sh
-redirect_output '<%= name %>'
+export JOB_NAME='<%= name %>'
+export JOB_DIR=/var/vcap/jobs/$JOB_NAME
 
+# the package that contains the application code
+WEBAPP_PACKAGE='<%= properties.webapp && properties.webapp.package || "rackapp" %>' 
+
+source $JOB_DIR/bin/ctl_utils.sh
+redirect_output $JOB_NAME
+
+if [[ "$WEBAPP_PACKAGE" = '' ]]
+then
+  echo 'ERROR: $WEBAPP_PACKAGE not set before bin/ctl_setup.sh'
+  exit 1
+fi
 
 export HOME=${HOME:-/home/vcap}
-export JOB_DIR=/var/vcap/jobs/<%= name %>
+WEBAPP_DIR=/var/vcap/packages/$WEBAPP_PACKAGE
 
 # Add all packages' /bin & /sbin into $PATH
 for package_bin_dir in $(ls -d /var/vcap/packages/*/{,s}bin)
@@ -22,9 +33,9 @@ done
 
 # Setup log, run and tmp folders
 
-RUN_DIR=/var/vcap/sys/run/<%= name %>
-LOG_DIR=/var/vcap/sys/log/<%= name %>
-TMPDIR=/var/vcap/sys/tmp/<%= name %>
+RUN_DIR=/var/vcap/sys/run/$JOB_NAME
+LOG_DIR=/var/vcap/sys/log/$JOB_NAME
+TMPDIR=/var/vcap/sys/tmp/$JOB_NAME
 for dir in $RUN_DIR $LOG_DIR $TMPDIR
 do
   mkdir -p ${dir}
@@ -34,5 +45,5 @@ done
 export C_INCLUDE_PATH=/var/vcap/packages/mysqlclient/include/mysql:/var/vcap/packages/sqlite/include:/var/vcap/packages/libpq/include
 export LIBRARY_PATH=/var/vcap/packages/mysqlclient/lib/mysql:/var/vcap/packages/sqlite/lib:/var/vcap/packages/libpq/lib
 
-PIDFILE=$RUN_DIR/<%= name %>.pid
+PIDFILE=$RUN_DIR/$JOB_NAME.pid
 
