webapp_ctl must be run as root (as monit)

diff --git a/jobs/webapp/templates/webapp_ctl.erb b/jobs/webapp/templates/webapp_ctl.erb
--- a/jobs/webapp/templates/webapp_ctl.erb
+++ b/jobs/webapp/templates/webapp_ctl.erb
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if [[ $EUID -ne 0 ]]; then
+  echo "ERROR: This script must be run as root" 1>&2
+  exit 1
+fi
+
 export RACKAPP_JOB_DIR=/var/vcap/jobs/webapp
 export RAILS_ENV=production
 export PATH=/var/vcap/packages/ruby/bin:$PATH
