Report the usage of uninitialized variables in webapp_ctl
Also remove unset $C_INCLUDE_PATH & $LIBRARY_PATH variables

diff --git a/jobs/webapp/templates/webapp_ctl.erb b/jobs/webapp/templates/webapp_ctl.erb
--- a/jobs/webapp/templates/webapp_ctl.erb
+++ b/jobs/webapp/templates/webapp_ctl.erb
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+set -e # exit immediately if a simple command exits with a non-zero status
+set -u # report the usage of uninitialized variables
+
 if [[ $EUID -ne 0 ]]; then
   echo "ERROR: This script must be run as root" 1>&2
   exit 1
@@ -41,8 +44,8 @@ export no_proxy='<%= properties.env.no_proxy %>'
 
 export CONFIG_DIR=$RACKAPP_JOB_DIR/config
 
-export C_INCLUDE_PATH=/var/vcap/packages/mysqlclient/include/mysql:/var/vcap/packages/sqlite/include:/var/vcap/packages/libpq/include:$C_INCLUDE_PATH
-export LIBRARY_PATH=/var/vcap/packages/mysqlclient/lib/mysql:/var/vcap/packages/sqlite/lib:/var/vcap/packages/libpq/lib:$LIBRARY_PATH
+export C_INCLUDE_PATH=/var/vcap/packages/mysqlclient/include/mysql:/var/vcap/packages/sqlite/include:/var/vcap/packages/libpq/include
+export LIBRARY_PATH=/var/vcap/packages/mysqlclient/lib/mysql:/var/vcap/packages/sqlite/lib:/var/vcap/packages/libpq/lib
 export LANG=en_US.UTF-8
 
 source /var/vcap/packages/common/utils.sh
